#include <Arduino.h>
#include <ArduinoJson.h>
#include <HTTPClient.h>
#include <SD.h>
#include <SPI.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <Wire.h>
#include <Adafruit_SHT4x.h>
#include <TFT_eSPI.h>
#include <driver/rtc_io.h>
#include <esp_mac.h>
#include <esp_sleep.h>
#include <esp_sntp.h>
#include <math.h>
#include <string.h>
#include <time.h>

#include "config.h"
#include "secrets.h"
#include "app_logic.h"
#include "app_logger.h"
#include "battery_gauge.h"
#include "ntp_sync.h"
#include "board_pins.h"
#include "hardware.h"
#include "local_time.h"
#include "wake_report.h"
#include "rtc_sync.h"
#include "wifi_sta.h"
#include "climate_sensor.h"
#include "sd_card.h"
#include "text_render.h"
#include "quiet_hours.h"
#include "sensors.h"
#include "pcf8563_utc.h"
#include "screenshot_bmp.h"
#include "timestamped_logger.h"
#include "theme.h"
#include "weather_data.h"
#include "weather_provider.h"
#include "canonical_weather.h"

#if RETERMINAL_MODEL == 1003
#include "fonts/Roboto_Bold90pt7b.h"
#elif RETERMINAL_MODEL == 1004
#include "fonts/Roboto_Bold72pt7b.h"
#else
#include "fonts/Roboto_Bold48pt7b.h"
#endif

SET_LOOP_TASK_STACK_SIZE(16U * 1024U);

#ifndef EPAPER_ENABLE
#error "Seeed_GFX did not select a reTerminal E-series driver; check common/include/driver.h"
#endif

TimestampedLogger appLog(Serial1);
// LOG is provided by app_logger.h; the definition above lives at namespace
// scope so the provider translation units can extern-link to it.

namespace {

using namespace ::board;
// Per-model palette, layout, dither and button-pin constants all live in
// include/theme.h; the using-directive keeps unqualified names (PANEL_WHITE,
// COLOR_SUN, PIN_BUTTON_GREEN, ...) working at every callsite below.
using namespace theme;

EPaper epaper;
Adafruit_SHT4x sht4;

bool sdReady = false;
bool screenshotRequested = false;
sensors::Readings sensorReadings;

RTC_DATA_ATTR time_t lastNtpSyncEpoch = 0;
bool quietSleepNotice = false;

// WeatherData / DailyForecast now live in weather_data.h so both the
// provider translation units and main.cpp share one definition.

// writeLittleEndian16/32, screenshotPaletteColor, and saveScreenshotBmp now
// live in common/include/screenshot_bmp.h and are invoked via the template
// screenshot::saveScreenshotBmp<EPaper>().

void updatePanel() {
  if (screenshotRequested && sdReady) {
    screenshot::saveScreenshotBmp(epaper, config::PANEL_WIDTH,
                                  config::PANEL_HEIGHT);
    screenshotRequested = false;
  }
  epaper.update();
}

// batteryPercentForVoltage() and the 16-sample averaging block used to be
// inline here; they now live in common/include/battery_gauge.h and are
// invoked via battery::measureBatteryFromAdc().

void selectSmallFont() {
  epaper.setTextSize(1);
#if RETERMINAL_MODEL == 1003
  epaper.setFreeFont(&FreeSansBold18pt7b);
#elif RETERMINAL_MODEL == 1004
  epaper.setFreeFont(&FreeSansBold12pt7b);
#else
  epaper.setFreeFont(&FreeSansBold9pt7b);
#endif
}

void selectSmallLightFont() {
  // Non-bold sibling of selectSmallFont for secondary labels that we
  // don't want to shout (e.g. "Overcast", forecast card details).
  epaper.setTextSize(1);
#if RETERMINAL_MODEL == 1003
  epaper.setFreeFont(&FreeSans18pt7b);
#elif RETERMINAL_MODEL == 1004
  epaper.setFreeFont(&FreeSans12pt7b);
#else
  epaper.setFreeFont(&FreeSans9pt7b);
#endif
}

// Optional smooth-font support for the footer location name (which may
// contain non-ASCII characters like "München", "São Paulo").  The font
// files live at /fonts/sans_bold_<size>.vlw on the SD card (shared with
// the xkcd viewer; generated by tools/fonts/make_vlw.py).  Sizes
// mirror the small-font fallback: DejaVu Sans Bold's cap-height is a
// little taller than FreeSansBold's for the same em, so em 16/20/30
// visually matches FreeSansBold9/12/18pt7b.
#if RETERMINAL_MODEL == 1003
constexpr int SMOOTH_FONT_SMALL_PX = 30;
constexpr const GFXfont* SMALL_SMOOTH_FALLBACK_FONT = &FreeSansBold18pt7b;
#elif RETERMINAL_MODEL == 1004
constexpr int SMOOTH_FONT_SMALL_PX = 20;
constexpr const GFXfont* SMALL_SMOOTH_FALLBACK_FONT = &FreeSansBold12pt7b;
#else
constexpr int SMOOTH_FONT_SMALL_PX = 16;
constexpr const GFXfont* SMALL_SMOOTH_FALLBACK_FONT = &FreeSansBold9pt7b;
#endif

static int g_currentSmoothSize = 0;
static bool g_smoothFontsUnavailable = false;

static bool smoothFontFileExists(int size) {
  if (!sdReady) return false;
  return sd_card::fileExists(String("/fonts/sans_bold_") + size + ".vlw");
}

static void unloadSmoothFontIfLoaded() {
  if (g_currentSmoothSize != 0) {
    epaper.unloadFont();
    g_currentSmoothSize = 0;
  }
}

// Install the smooth font at `size` (pixels) for the next drawString
// calls.  Falls back to `fallback` (a GFX FreeFont at roughly the same
// cap-height) when the SD is not mounted, the .vlw is missing, or a
// previous load has already failed this boot.  Mirrors the xkcd-viewer
// helper of the same shape - keeps behaviour consistent across apps.
static void applySmoothFont(int size, const GFXfont* fallback) {
  if (g_smoothFontsUnavailable || !sdReady) {
    unloadSmoothFontIfLoaded();
    epaper.setFreeFont(fallback);
    return;
  }
  if (g_currentSmoothSize == size) return;
  if (g_currentSmoothSize != 0) {
    epaper.unloadFont();
    g_currentSmoothSize = 0;
  }
  if (!smoothFontFileExists(size)) {
    LOG.printf("[font] /fonts/sans_bold_%d.vlw missing; falling back to GFX font\n",
               size);
    g_smoothFontsUnavailable = true;
    epaper.setFreeFont(fallback);
    return;
  }
  epaper.setFreeFont(nullptr);
  const uint32_t t0 = millis();
  // TFT_eSPI::loadFont builds "/" + name + ".vlw" internally, so pass
  // the subdir as part of the name to get "/fonts/sans_bold_XX.vlw".
  epaper.loadFont(String("fonts/sans_bold_") + size, SD);
  g_currentSmoothSize = size;
  LOG.printf("[font] loaded sans_bold_%d in %lu ms (yAdvance=%u ascent=%u descent=%u)\n",
             size, (unsigned long)(millis() - t0),
             (unsigned)epaper.gFont.yAdvance,
             (unsigned)epaper.gFont.ascent,
             (unsigned)epaper.gFont.descent);
}

// Select the smooth (Unicode-capable) small font.  Its cap-height
// matches selectSmallFont() so switching between the two keeps the
// header and footer visually consistent.  Used for the header title,
// the footer provider label, and the footer location name.
void selectSmallSmoothFont() {
  epaper.setTextSize(1);
  applySmoothFont(SMOOTH_FONT_SMALL_PX, SMALL_SMOOTH_FALLBACK_FONT);
}

// TFT_eSPI's MC/ML/MR datums center the smooth font's yAdvance box on
// the requested y, but DejaVu Sans Bold's ascent is much larger than
// its descent, so the visual cap-center sits a few pixels above the
// box center.  This helper returns the y offset (in pixels) needed to
// align the cap-center with the caller's y.  Returns 0 when a smooth
// font is not loaded so GFX callers are unaffected.
static int smoothCenterYAdjust() {
  if (g_currentSmoothSize == 0) return 0;
  const int yA = static_cast<int>(epaper.gFont.yAdvance);
  const int mA = static_cast<int>(epaper.gFont.maxAscent);
  const int a  = static_cast<int>(epaper.gFont.ascent);
  // Approximate cap-height as ascent * 0.78 (DejaVu Sans Bold).
  return (yA / 2) - mA + (a * 78 / 200);
}

void selectUpdateTimeFont() {
#if RETERMINAL_MODEL == 1003 || RETERMINAL_MODEL == 1004
  epaper.setFreeFont(&FreeSans9pt7b);
#else
  epaper.setFreeFont(nullptr);
  epaper.setTextFont(2);
#endif
}

void selectMediumFont() {
  epaper.setTextSize(1);
#if RETERMINAL_MODEL == 1003
  epaper.setFreeFont(&FreeSansBold24pt7b);
#elif RETERMINAL_MODEL == 1004
  epaper.setFreeFont(&FreeSansBold18pt7b);
#else
  epaper.setFreeFont(&FreeSansBold12pt7b);
#endif
}

void selectLargeTemperatureFont() {
  // Each panel gets a native-resolution numeral font matching the physical
  // size of the formerly magnified 24-point font, without bitmap scaling.
  epaper.setTextSize(1);
#if RETERMINAL_MODEL == 1003
  epaper.setFreeFont(&Roboto_Bold90pt7b);
#elif RETERMINAL_MODEL == 1004
  epaper.setFreeFont(&Roboto_Bold72pt7b);
#else
  epaper.setFreeFont(&Roboto_Bold48pt7b);
#endif
}

void drawBadges(uint32_t background = PANEL_WHITE,
                bool fillTextBackground = true,
                const String* weatherUpdateTime = nullptr) {
  epaper.setTextColor(PANEL_BLACK, background, fillTextBackground);
  selectSmallFont();

  const int statusCenterY = config::ui(24);
  const int edgeInset = config::ui(6);
  epaper.setTextDatum(ML_DATUM);
  String climate = "--.-C  --%";
  if (sensorReadings.climateValid) {
    climate = String(sensorReadings.temperatureC, 1) + "C  " +
              String(sensorReadings.humidityPct, 0) + "%";
  }
  epaper.drawString(climate, edgeInset, statusCenterY, 1);

  const String percent = sensorReadings.batteryPct >= 0 ? String(sensorReadings.batteryPct) + "%" : "--%";
  const int w = config::ui(22);
  const int h = config::ui(12);
  const int terminalWidth = max(3, config::ui(5));
  const int x = config::PANEL_WIDTH - edgeInset - terminalWidth - w;
  const int gaugeCenterY = statusCenterY + 2;
  const int y = gaugeCenterY - h / 2;
  const int outline = max(1, config::ui(1));
  const int terminalHeight = max(3, config::ui(5));

  epaper.setTextDatum(MR_DATUM);
  const int percentRightX = x - config::ui(9);
  epaper.drawString(percent, percentRightX, statusCenterY, 1);
  if (config::DEBUG_SHOW_STATUS_BADGES && weatherUpdateTime != nullptr &&
      !weatherUpdateTime->isEmpty()) {
    const int separator = weatherUpdateTime->indexOf('T');
    if (separator >= 10 &&
        weatherUpdateTime->length() >= static_cast<size_t>(separator + 6)) {
      const String updateDate = weatherUpdateTime->substring(5, 10);
      const String updateClock =
          weatherUpdateTime->substring(separator + 1, separator + 6);
      const int updateRightX =
          percentRightX - epaper.textWidth(percent, 1) - config::ui(10);
      selectUpdateTimeFont();
      epaper.setTextColor(PANEL_BLACK, background, fillTextBackground);
      const int lineCenterDistance = epaper.fontHeight(1) + 1;
      const int dateY = statusCenterY - lineCenterDistance / 2;
      const int timeY = dateY + lineCenterDistance;
      epaper.drawString(updateDate, updateRightX, dateY, 1);
      epaper.drawString(updateClock, updateRightX, timeY, 1);
    }
  }
  text_render::drawBatteryGauge(epaper, x, y, w, h, sensorReadings.batteryPct, outline,
                                terminalWidth, terminalHeight, PANEL_BLACK, PANEL_WHITE,
                                sensorReadings.chargerValid && sensorReadings.externalPower);
  epaper.setTextSize(1);
  epaper.setFreeFont(nullptr);
  epaper.setTextFont(2);
}

void renderStatus(const String& message, const String& detail = "",
                  const String& lineAbove = "") {
  epaper.fillSprite(PANEL_WHITE);
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(MC_DATUM);
  if (!lineAbove.isEmpty()) {
    selectSmallFont();
    epaper.drawString(
        text_render::ellipsize(epaper, lineAbove, config::PANEL_WIDTH - config::ui(60)),
        config::PANEL_WIDTH / 2,
        config::PANEL_HEIGHT / 2 - config::ui(55), 1);
  }
  selectMediumFont();
  epaper.drawString(
      text_render::ellipsize(epaper, message, config::PANEL_WIDTH - config::ui(60)),
      config::PANEL_WIDTH / 2,
      config::PANEL_HEIGHT / 2 - config::ui(15), 1);
  if (!detail.isEmpty()) {
    selectSmallFont();
    epaper.drawString(
        text_render::ellipsize(epaper, detail, config::PANEL_WIDTH - config::ui(60)),
        config::PANEL_WIDTH / 2,
        config::PANEL_HEIGHT / 2 + config::ui(25), 1);
  }
  epaper.setTextSize(1);
  epaper.setFreeFont(nullptr);
  epaper.setTextFont(2);
  drawBadges();
  updatePanel();
}

// NTP sync helpers now live in common/include/ntp_sync.h. The wrapper below
bool parseWeather(const String& body, WeatherData& weather) {
  if (config::WEATHER_PROVIDER == config::WeatherProvider::QWeather) {
    return weather_provider::parseQWeather(body, weather);
  }
  return weather_provider::parseOpenMeteo(body, weather);
}

bool fetchWeather(WeatherData& weather, String& responseBody,
                  String& failureReason, bool bypassHttpCache = false) {
  if (config::WEATHER_PROVIDER == config::WeatherProvider::QWeather) {
    return weather_provider::fetchQWeather(weather, responseBody,
                                           failureReason, bypassHttpCache);
  }
  return weather_provider::fetchOpenMeteo(weather, responseBody,
                                          failureReason, bypassHttpCache);
}

bool loadCachedWeather(WeatherData& weather, String& failureReason,
                       uint64_t maxAgeSeconds = config::CACHE_MAX_AGE_SECONDS) {
  failureReason = "";
  String body;
  if (!sdReady) {
    failureReason = "No SD forecast cache is available";
    return false;
  }
  if (!sd_card::fileExists(config::FORECAST_CACHE)) {
    failureReason = "No saved forecast is available";
    return false;
  }
  if (!sd_card::readFile(config::FORECAST_CACHE, body, 128U * 1024U)) {
    failureReason = "Saved forecast could not be read";
    return false;
  }
  if (!canonical_weather::parse(body, weather)) {
    failureReason = "Saved forecast is invalid";
    return false;
  }

  const time_t now = time(nullptr);
  time_t forecastTime = 0;
  if (!local_time::clockIsValid()) {
    failureReason = "Cannot verify saved forecast age";
    LOG.printf("[cache] %s\n", failureReason.c_str());
    return false;
  }
  if (!local_time::parseIso8601Local(weather.updateTime.c_str(), forecastTime)) {
    failureReason = "Saved forecast time is invalid";
    LOG.printf("[cache] %s: %s\n", failureReason.c_str(),
               weather.updateTime.c_str());
    return false;
  }
  if (!app_logic::cachedDataFresh(
          true, now, forecastTime, maxAgeSeconds)) {
    if (now < forecastTime) {
      failureReason = "Saved forecast time is in the future";
    } else {
      const uint64_t ageMinutes =
          static_cast<uint64_t>(now - forecastTime + 59) / 60;
      failureReason =
          "Saved forecast is " + String(ageMinutes) + " minutes old";
    }
    LOG.printf("[cache] rejected: %s (maximum %llu seconds)\n",
               failureReason.c_str(),
               static_cast<unsigned long long>(maxAgeSeconds));
    return false;
  }

  weather.fromCache = true;
  LOG.printf("[cache] using forecast updated %s\n",
             weather.updateTime.c_str());
  return true;
}

String uvDescription(float uv) {
  if (!isfinite(uv)) return "--";
  if (uv < 3.0f) return "Low";
  if (uv < 6.0f) return "Moderate";
  if (uv < 8.0f) return "High";
  if (uv < 11.0f) return "Very high";
  return "Extreme";
}

String updateClock(const String& isoTime) {
  const int separator = isoTime.indexOf('T');
  if (separator >= 0 && isoTime.length() >= static_cast<size_t>(separator + 6))
    return isoTime.substring(separator + 1, separator + 6);
  return "";
}

String weatherAgeText(const String& isoTime) {
  time_t forecastTime = 0;
  if (!local_time::clockIsValid() || !local_time::parseIso8601Local(isoTime.c_str(), forecastTime))
    return "";

  const int64_t roundedMinutes = app_logic::roundedAgeMinutes(
      static_cast<int64_t>(time(nullptr)),
      static_cast<int64_t>(forecastTime));
  if (roundedMinutes < 0) return "";
  if (roundedMinutes == 0) return "just now";

  const int64_t hours = roundedMinutes / 60;
  const int64_t minutes = roundedMinutes % 60;
  String age;
  if (hours > 0) {
    age = String(static_cast<long long>(hours)) +
          (hours == 1 ? " hour" : " hours");
    if (minutes > 0) {
      age += " and " + String(static_cast<long long>(minutes)) +
             (minutes == 1 ? " minute" : " minutes");
    }
  } else {
    age = String(static_cast<long long>(minutes)) +
          (minutes == 1 ? " minute" : " minutes");
  }
  return age + " ago";
}

String dayLabel(uint8_t index, const String& date) {
  if (index == 0) return "Today";
  if (index == 1) return "Tomorrow";
  if (date.length() >= 10) return date.substring(5);
  return "Day " + String(index + 1);
}

String nextRainWhen(const WeatherData& weather) {
  const String clock = updateClock(weather.nextRainTime);
  if (clock.isEmpty()) return "";
  if (weather.nextRainTime.length() >= 10) {
    const String date = weather.nextRainTime.substring(0, 10);
    if (!weather.days[0].date.isEmpty() && date == weather.days[0].date)
      return clock;
    if (!weather.days[1].date.isEmpty() && date == weather.days[1].date)
      return "tomorrow " + clock;
    return weather.nextRainTime.substring(5, 10) + " " + clock;
  }
  return clock;
}

String rainSummary(const WeatherData& weather) {
  if (weather.rainExpected) {
    const String when = nextRainWhen(weather);
    if (when.startsWith("tomorrow "))
      return "Rain tomorrow " + when.substring(9);
    String summary = "Rain " + when;
    if (weather.nextRainProbability >= 0) {
      summary += " (" + String(weather.nextRainProbability) + "%)";
    }
    return summary;
  }
  if (weather.rainTimingAvailable) {
    return "No rain forecast in " +
           String(config::RAIN_FORECAST_HOURS) + "h";
  }
  return "";
}

void thickLine(int x1, int y1, int x2, int y2, int thickness,
               uint32_t color) {
  if (thickness <= 1) {
    epaper.drawLine(x1, y1, x2, y2, color);
    return;
  }
  // Axis-aligned rays use rectangles so their opposing directions have
  // exactly the same rasterized width. Triangle edge rules can otherwise
  // make a right-to-left horizontal line one pixel thinner.
  if (y1 == y2) {
    const int left = min(x1, x2);
    epaper.fillRect(left, y1 - thickness / 2,
                    abs(x2 - x1) + 1, thickness, color);
    return;
  }
  if (x1 == x2) {
    const int top = min(y1, y2);
    epaper.fillRect(x1 - thickness / 2, top,
                    thickness, abs(y2 - y1) + 1, color);
    return;
  }
  const float dx = static_cast<float>(x2 - x1);
  const float dy = static_cast<float>(y2 - y1);
  const float length = sqrtf(dx * dx + dy * dy);
  if (length < 1.0f) {
    epaper.fillCircle(x1, y1, max(1, thickness / 2), color);
    return;
  }
  const float half = thickness / 2.0f;
  const int px = static_cast<int>(roundf(-dy * half / length));
  const int py = static_cast<int>(roundf(dx * half / length));
  epaper.fillTriangle(x1 + px, y1 + py, x1 - px, y1 - py,
                      x2 + px, y2 + py, color);
  epaper.fillTriangle(x1 - px, y1 - py, x2 - px, y2 - py,
                      x2 + px, y2 + py, color);
}

void drawSun(int cx, int cy, int radius, uint32_t color) {
  // Keep the solar disc open and bright, with the panel color used only for
  // its outline and rays.
  epaper.fillCircle(cx, cy, radius, PANEL_WHITE);
  const int outline = max(1, radius / 12);
  for (int inset = 0; inset < outline; ++inset) {
    epaper.drawCircle(cx, cy, radius - inset, color);
  }
  const int inner = radius + max(3, radius / 2);
  const int outer = radius + max(7, radius);
  const int thickness = max(1, radius / 8);
  for (int angle = 0; angle < 360; angle += 45) {
    const float radians = angle * PI / 180.0f;
    thickLine(cx + cosf(radians) * inner, cy + sinf(radians) * inner,
              cx + cosf(radians) * outer, cy + sinf(radians) * outer,
              thickness, color);
  }
}

void drawMoon(int cx, int cy, int radius) {
  epaper.fillCircle(cx, cy, radius, PANEL_BLACK);
  epaper.fillCircle(cx + radius / 2, cy - radius / 3, radius, PANEL_WHITE);
}

void drawCloud(int cx, int cy, int size) {
  const int baseY = cy + size / 7;
  epaper.fillCircle(cx - size / 5, cy, size / 5, PANEL_LIGHT);
  epaper.fillCircle(cx + size / 10, cy - size / 8, size / 4, PANEL_LIGHT);
  epaper.fillCircle(cx + size / 3, cy + size / 20, size / 6, PANEL_LIGHT);
  epaper.fillRect(cx - size / 3, cy, size * 2 / 3, size / 4, PANEL_LIGHT);
  epaper.drawCircle(cx - size / 5, cy, size / 5, PANEL_BLACK);
  epaper.drawCircle(cx + size / 10, cy - size / 8, size / 4, PANEL_BLACK);
  epaper.drawCircle(cx + size / 3, cy + size / 20, size / 6, PANEL_BLACK);
  thickLine(cx - size / 3, baseY, cx + size / 2, baseY,
            max(1, size / 25), PANEL_BLACK);
}

void drawWeatherIcon(int cx, int cy, int size, int code, bool isDay = true) {
  // For a clear sky, the ray tips now span approximately the full requested
  // size instead of occupying less than half of the icon box.
  const int radius = max(4, size / 4);
  if (code == 0) {
    if (isDay) drawSun(cx, cy, radius, COLOR_SUN);
    else drawMoon(cx, cy, radius);
    return;
  }
  if (code == 1 || code == 2) {
    drawSun(cx - size / 5, cy - size / 5, max(3, radius * 3 / 4),
            COLOR_SUN);
    drawCloud(cx + size / 10, cy + size / 10, size);
    return;
  }

  // Only shift the cloud up when precipitation strokes render below
  // it; for a plain overcast/fog code the cloud stays centered on cy.
  const bool hasPrecipBelow =
      (code >= 51 && code <= 67) || (code >= 71 && code <= 77) ||
      (code >= 80 && code <= 86) || (code >= 95);
  const int cloudCy = hasPrecipBelow ? cy - size / 8 : cy;
  drawCloud(cx, cloudCy, size);
  if (code == 45 || code == 48) {
    for (int i = 0; i < 3; ++i) {
      const int y = cy + size / 4 + i * max(3, size / 8);
      thickLine(cx - size / 3, y, cx + size / 3, y,
                max(1, size / 30), PANEL_MUTED);
    }
  } else if ((code >= 51 && code <= 67) ||
             (code >= 80 && code <= 82)) {
    for (int i = -1; i <= 1; ++i) {
      const int x = cx + i * size / 4;
      thickLine(x, cy + size / 5, x - size / 12, cy + size / 2,
                max(1, size / 24), COLOR_RAIN);
    }
  } else if ((code >= 71 && code <= 77) ||
             (code >= 85 && code <= 86)) {
    for (int i = -1; i <= 1; ++i) {
      const int x = cx + i * size / 4;
      const int y = cy + size / 3;
      thickLine(x - size / 12, y, x + size / 12, y,
                max(1, size / 30), COLOR_RAIN);
      thickLine(x, y - size / 12, x, y + size / 12,
                max(1, size / 30), COLOR_RAIN);
    }
  } else if (code >= 95) {
    const int top = cy + size / 8;
    epaper.fillTriangle(cx, top, cx - size / 8, top + size / 4,
                        cx + size / 16, top + size / 4, COLOR_ALERT);
    epaper.fillTriangle(cx + size / 16, top + size / 4,
                        cx - size / 16, top + size / 2,
                        cx + size / 5, top + size / 5, COLOR_ALERT);
  }
}

void drawLargeTemperature(float temperature, int cx, int cy) {
  const int rounded = static_cast<int>(roundf(temperature));
  const bool negative = rounded < 0;
  const String value = String(abs(rounded));
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(MC_DATUM);
  selectLargeTemperatureFont();
  const int textWidth = epaper.textWidth(value, 1);
  const int textHeight = epaper.fontHeight(1);
  const int minusWidth = negative ? max(4, textHeight / 3) : 0;
  const int minusGap = negative ? max(2, textHeight / 12) : 0;
  const int valueCenterX = cx + (minusWidth + minusGap) / 2;
  epaper.drawString(value, valueCenterX, cy, 1);
  if (negative) {
    const int totalWidth = minusWidth + minusGap + textWidth;
    const int minusLeft = cx - totalWidth / 2;
    thickLine(minusLeft, cy, minusLeft + minusWidth, cy,
              max(2, textHeight / 18), PANEL_BLACK);
  }
  const int degreeRadius = max(3, textHeight / 15);
  epaper.drawCircle(valueCenterX + textWidth / 2 + degreeRadius * 2,
                    cy - textHeight / 3, degreeRadius, PANEL_BLACK);
  epaper.setTextSize(1);
  epaper.setFreeFont(nullptr);
  epaper.setTextFont(1);
}

void drawHeader(const WeatherData& weather) {
  const int height = config::ui(45);
  epaper.fillRect(0, 0, config::PANEL_WIDTH, height, PANEL_WHITE);
  drawBadges(PANEL_WHITE, true, &weather.updateTime);
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(MC_DATUM);
  String heading;
  const String age = weatherAgeText(weather.updateTime);
  if (!age.isEmpty()) {
    heading = "Weather " + age;
  } else {
    heading = "Weather";
  }
  if (quietSleepNotice) {
    heading = "Weather - sleeping until " + quiet_hours::endLabel();
  }
  // Render the header title in the shared smooth (Unicode-capable) font
  // so it matches the footer's provider label and location name.
  selectSmallSmoothFont();
  epaper.drawString(
      text_render::ellipsize(epaper, text_render::displayText(heading), config::PANEL_WIDTH - config::ui(380)),
      config::PANEL_WIDTH / 2, config::ui(24) + smoothCenterYAdjust(), 1);
  // Unload before returning: the main-body renders that follow use GFX
  // fonts, but TFT_eSPI's drawString stays on the smooth-font path as
  // long as one is loaded, which would shrink e.g. the large outdoor
  // temperature down to 16 px.  renderFooter reloads the same size.
  unloadSmoothFontIfLoaded();
  epaper.drawFastHLine(config::ui(10), config::ui(44),
                       config::PANEL_WIDTH - config::ui(20), PANEL_BLACK);
}

void drawForecastCard(const DailyForecast& day, uint8_t index,
                      int left, int top, int width, int height) {
  const int centerX = left + width / 2;
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(TC_DATUM);
  selectMediumFont();
  epaper.drawString(dayLabel(index, day.date), centerX,
                    top + config::ui(7), 1);

  const int iconSize = min(width / 7, config::ui(32));
  drawWeatherIcon(centerX, top + config::ui(55), iconSize,
                  day.weatherCode, true);

  selectSmallFont();
  epaper.drawString(
      text_render::ellipsize(epaper, app_logic::conditionName(day.weatherCode), width - config::ui(12)),
      centerX, top + config::ui(83), 1);
  const String range =
      String(static_cast<int>(roundf(day.minimumC))) + "C  /  " +
      String(static_cast<int>(roundf(day.maximumC))) + "C";
  epaper.drawString(range, centerX, top + config::ui(107), 1);
  epaper.setTextColor(PANEL_SECONDARY_TEXT, PANEL_WHITE, true);
  const String extra =
      "Rain " + String(day.precipitationProbability) + "%   UV " +
      String(day.uvMaximum, 1) + " " + uvDescription(day.uvMaximum);
  epaper.drawString(text_render::ellipsize(epaper, extra, width - config::ui(12)), centerX,
                    top + config::ui(130), 1);
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
}

void renderLandscape(const WeatherData& weather) {
  const int mainTop = config::ui(48);
  const int mainBottom = config::PANEL_HEIGHT * 62 / 100;
  const int mainCenterY = (mainTop + mainBottom) / 2;
  const int leftDividerX = config::PANEL_WIDTH * 34 / 100;
  // Center the hero icon inside the left pane (0 .. leftDividerX)
  // instead of at a hard-coded 19% offset that was slightly off.
  const int iconX = leftDividerX / 2;
  const int temperatureX = config::PANEL_WIDTH * 49 / 100;
  const int detailX = config::PANEL_WIDTH * 83 / 100;

  drawWeatherIcon(iconX, mainCenterY,
                  min(config::PANEL_WIDTH * 27 / 100,
                      (mainBottom - mainTop) * 72 / 100),
                  weather.weatherCode, weather.isDay);
  epaper.drawFastVLine(leftDividerX,
                       mainTop + config::ui(12),
                       mainBottom - mainTop - config::ui(24), PANEL_MUTED);

  drawLargeTemperature(weather.temperatureC, temperatureX,
                       mainCenterY - config::ui(13));
  // "Outdoor temperature" is dropped -- the giant number next to the
  // weather icon already communicates the same thing.  The condition
  // name takes its slot in bold black instead.
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(TC_DATUM);
  selectSmallFont();
  epaper.drawString(app_logic::conditionName(weather.weatherCode), temperatureX,
                    mainCenterY + config::ui(57), 1);

  epaper.drawFastVLine(config::PANEL_WIDTH * 66 / 100,
                       mainTop + config::ui(12),
                       mainBottom - mainTop - config::ui(24), PANEL_MUTED);
  epaper.setTextDatum(MC_DATUM);
  selectMediumFont();
  epaper.drawString(
      String(static_cast<int>(roundf(weather.apparentC))) + "C",
      detailX, mainCenterY - config::ui(66), 1);
  // Secondary captions and secondary detail lines: bold but drawn in a
  // muted grey so hierarchy comes from tone, not weight.  Keeps the
  // page from feeling shouty without dropping to the anaemic-looking
  // FreeSans Regular bitmap face.
  epaper.setTextColor(PANEL_SECONDARY_TEXT, PANEL_WHITE, true);
  selectSmallFont();
  epaper.drawString("Feels like", detailX,
                    mainCenterY - config::ui(40), 1);

  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  selectMediumFont();
  epaper.drawString(
      String(static_cast<int>(roundf(weather.humidityPct))) + "%",
      detailX, mainCenterY + config::ui(5), 1);
  epaper.setTextColor(PANEL_SECONDARY_TEXT, PANEL_WHITE, true);
  selectSmallFont();
  epaper.drawString("Outdoor humidity", detailX,
                    mainCenterY + config::ui(31), 1);

  const int detailWidth = config::PANEL_WIDTH * 31 / 100;
  epaper.drawString(
      text_render::ellipsize(epaper, rainSummary(weather), detailWidth),
      detailX, mainCenterY + config::ui(67), 1);
  epaper.drawString(
      "Wind " + String(weather.windKmh, 0) + " km/h", detailX,
      mainCenterY + config::ui(101), 1);
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);

  epaper.drawFastHLine(config::ui(10), mainBottom,
                       config::PANEL_WIDTH - config::ui(20), PANEL_MUTED);
  const int forecastTop = mainBottom + config::ui(4);
  const int footerTop = config::PANEL_HEIGHT - config::ui(30);
  const int cardWidth =
      (config::PANEL_WIDTH - config::ui(20)) / config::FORECAST_DAYS;
  for (uint8_t i = 0; i < config::FORECAST_DAYS; ++i) {
    const int left = config::ui(10) + i * cardWidth;
    if (i > 0) {
      epaper.drawFastVLine(left, forecastTop + config::ui(8),
                           footerTop - forecastTop - config::ui(12),
                           PANEL_LIGHT);
    }
    drawForecastCard(weather.days[i], i, left, forecastTop, cardWidth,
                     footerTop - forecastTop);
  }
}

void drawPortraitForecastRow(const DailyForecast& day, uint8_t index,
                             int top, int height) {
  const int margin = config::ui(14);
  const int iconX = config::PANEL_WIDTH * 18 / 100;
  const int textX = config::PANEL_WIDTH * 37 / 100;
  const int valuesX = config::PANEL_WIDTH * 78 / 100;
  const int centerY = top + height / 2;

  epaper.drawFastHLine(margin, top, config::PANEL_WIDTH - 2 * margin,
                       PANEL_LIGHT);
  drawWeatherIcon(iconX, centerY, min(height / 5, config::ui(40)),
                  day.weatherCode, true);
  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(ML_DATUM);
  selectMediumFont();
  epaper.drawString(dayLabel(index, day.date), textX,
                    centerY - config::ui(28), 1);
  selectSmallFont();
  epaper.drawString(
      text_render::ellipsize(epaper, app_logic::conditionName(day.weatherCode),
                config::PANEL_WIDTH * 36 / 100),
      textX, centerY + config::ui(4), 1);
  epaper.drawString(
      "Rain " + String(day.precipitationProbability) + "%  UV " +
          String(day.uvMaximum, 1),
      textX, centerY + config::ui(31), 1);

  epaper.setTextDatum(MC_DATUM);
  selectMediumFont();
  epaper.drawString(
      String(static_cast<int>(roundf(day.minimumC))) + "C / " +
          String(static_cast<int>(roundf(day.maximumC))) + "C",
      valuesX, centerY - config::ui(8), 1);
  selectSmallFont();
  epaper.drawString("Low / High", valuesX,
                    centerY + config::ui(25), 1);
}

void renderPortrait(const WeatherData& weather) {
  const int mainTop = config::ui(50);
  const int mainBottom = config::PANEL_HEIGHT * 43 / 100;
  const int mainCenterY = (mainTop + mainBottom) / 2;

  drawWeatherIcon(config::PANEL_WIDTH * 24 / 100,
                  mainCenterY - config::ui(25),
                  min(config::PANEL_WIDTH * 35 / 100,
                      (mainBottom - mainTop) * 72 / 100),
                  weather.weatherCode, weather.isDay);
  drawLargeTemperature(weather.temperatureC,
                       config::PANEL_WIDTH * 67 / 100,
                       mainCenterY - config::ui(38));

  epaper.setTextColor(PANEL_BLACK, PANEL_WHITE, true);
  epaper.setTextDatum(MC_DATUM);
  selectMediumFont();
  epaper.drawString(app_logic::conditionName(weather.weatherCode),
                    config::PANEL_WIDTH / 2,
                    mainCenterY + config::ui(72), 1);
  selectSmallFont();
  const String details =
      "Feels " + String(weather.apparentC, 0) + "C   Humidity " +
      String(weather.humidityPct, 0) + "%   Wind " +
      String(weather.windKmh, 0) + " km/h";
  epaper.drawString(
      text_render::ellipsize(epaper, details, config::PANEL_WIDTH - config::ui(40)),
      config::PANEL_WIDTH / 2, mainCenterY + config::ui(108), 1);
  epaper.drawString(
      text_render::ellipsize(epaper, rainSummary(weather),
                config::PANEL_WIDTH - config::ui(40)),
      config::PANEL_WIDTH / 2, mainCenterY + config::ui(142), 1);

  const int footerTop = config::PANEL_HEIGHT - config::ui(34);
  const int rowHeight =
      (footerTop - mainBottom) / config::FORECAST_DAYS;
  for (uint8_t i = 0; i < config::FORECAST_DAYS; ++i) {
    drawPortraitForecastRow(weather.days[i], i,
                            mainBottom + i * rowHeight, rowHeight);
  }
}

void renderFooter() {
  const int top = config::PANEL_HEIGHT - config::ui(30);
  // Anchor the label baseline to the actual band vertical center so the
  // text visually sits in the middle of the strip (previously the label
  // was 2 px above centre for a 30 px band, which was noticeable on
  // solid backgrounds).
  const int labelY = (top + config::PANEL_HEIGHT) / 2;
  text_render::fillStatusBackground(epaper, top, config::PANEL_HEIGHT - top, config::PANEL_WIDTH, config::PANEL_HEIGHT, PANEL_STATUS_BACKGROUND, PANEL_STATUS_DITHERED, PANEL_STATUS_DITHER_COLOR, PANEL_STATUS_DITHER_THRESHOLD);
  epaper.drawFastHLine(config::ui(10), top,
                       config::PANEL_WIDTH - config::ui(20), PANEL_MUTED);
  selectSmallSmoothFont();
  // Smooth fonts always anti-alias against an explicit background color;
  // in transparent mode (bgFill=false) the AA blender still needs the
  // correct bg or every glyph collapses to solid PANEL_BLACK.  On a
  // dithered status bar we keep bgFill off so glyphs don't punch solid
  // rectangles through the dither pattern; on solid bars we fill for
  // crisp edges.
  epaper.setTextColor(PANEL_BLACK, PANEL_STATUS_BACKGROUND, !PANEL_STATUS_DITHERED);
  const int footerYAdjust = smoothCenterYAdjust();
  epaper.setTextDatum(ML_DATUM);
  epaper.drawString(text_render::displayText(String("Weather data: ") + weather_provider::name()),
                    config::ui(12), labelY + footerYAdjust, 1);
  epaper.setTextDatum(MR_DATUM);
  epaper.drawString(text_render::displayText(String(config::LOCATION_NAME)),
                    config::PANEL_WIDTH - config::ui(12),
                    labelY + footerYAdjust, 1);
  // Restore the GFX small font in case any later footer additions rely
  // on it; also releases the .vlw resources so the next full-panel
  // repaint doesn't hold onto them.
  unloadSmoothFontIfLoaded();
  selectSmallFont();
}

void drawAlertBar(const WeatherData& weather) {
  if (weather.alertTitle.isEmpty()) return;
  const int top = config::ui(46);
  const int height = config::ui(22);
  epaper.fillRect(0, top, config::PANEL_WIDTH, height, PANEL_LIGHT);
  epaper.drawFastHLine(config::ui(10), top + height,
                       config::PANEL_WIDTH - config::ui(20), PANEL_MUTED);
  epaper.setTextColor(PANEL_BLACK, PANEL_LIGHT, true);
  epaper.setTextDatum(MC_DATUM);
  selectSmallFont();
  String line = "! Alert: " + weather.alertTitle;
  if (weather.alertOtherCount > 0) {
    line += " (+" + String(weather.alertOtherCount) + " more)";
  }
  epaper.drawString(
      text_render::ellipsize(epaper, line,
                             config::PANEL_WIDTH - config::ui(24)),
      config::PANEL_WIDTH / 2, top + height / 2, 1);
}

void renderWeather(const WeatherData& weather) {
  epaper.fillSprite(PANEL_WHITE);
  drawHeader(weather);
  drawAlertBar(weather);
#if RETERMINAL_MODEL == 1004
  renderPortrait(weather);
#else
  renderLandscape(weather);
#endif
  renderFooter();
  epaper.setTextSize(1);
  epaper.setFreeFont(nullptr);
  epaper.setTextFont(2);
  LOG.println("[render] refreshing weather panel");
  updatePanel();
  LOG.println("[render] complete");
}

void powerDownAndSleep(uint64_t sleepSeconds = config::SLEEP_SECONDS,
                       bool timerWakeEnabled = true) {
  wifi_sta::disable();
  if (sdReady) SD.end();
  pinMode(PIN_SD_ENABLE, OUTPUT);
  digitalWrite(PIN_SD_ENABLE, LOW);
  pinMode(PIN_BATTERY_ENABLE, OUTPUT);
  digitalWrite(PIN_BATTERY_ENABLE, LOW);

  pinMode(PIN_BUTTON_GREEN, INPUT_PULLUP);
  pinMode(PIN_BUTTON_RIGHT, INPUT_PULLUP);
  pinMode(PIN_BUTTON_LEFT, INPUT_PULLUP);
  const uint32_t releaseStarted = millis();
  while ((!digitalRead(PIN_BUTTON_GREEN) ||
          !digitalRead(PIN_BUTTON_RIGHT) ||
          !digitalRead(PIN_BUTTON_LEFT)) &&
         millis() - releaseStarted < 2000) {
    delay(10);
  }

  const int wakePins[] = {
      PIN_BUTTON_GREEN, PIN_BUTTON_RIGHT, PIN_BUTTON_LEFT};
  bool rtcPinsReady = true;
  for (const int pin : wakePins) {
    const gpio_num_t gpio = static_cast<gpio_num_t>(pin);
    rtc_gpio_hold_dis(gpio);
    rtcPinsReady =
        rtc_gpio_init(gpio) == ESP_OK &&
        rtc_gpio_set_direction(gpio, RTC_GPIO_MODE_INPUT_ONLY) == ESP_OK &&
        rtc_gpio_pullup_en(gpio) == ESP_OK &&
        rtc_gpio_pulldown_dis(gpio) == ESP_OK &&
        rtcPinsReady;
  }
  const uint64_t wakeMask =
      (1ULL << PIN_BUTTON_GREEN) | (1ULL << PIN_BUTTON_RIGHT) |
      (1ULL << PIN_BUTTON_LEFT);
  const esp_err_t buttonWakeResult =
      rtcPinsReady
          ? esp_sleep_enable_ext1_wakeup(wakeMask, ESP_EXT1_WAKEUP_ANY_LOW)
          : ESP_FAIL;
  const esp_err_t timerWakeResult =
      timerWakeEnabled
          ? esp_sleep_enable_timer_wakeup(sleepSeconds * 1000000ULL)
          : esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER);
  LOG.printf("[sleep] wake config: buttons=%s timer=%s levels=%d/%d/%d\n",
             esp_err_to_name(buttonWakeResult),
             timerWakeEnabled ? esp_err_to_name(timerWakeResult) : "disabled",
             digitalRead(PIN_BUTTON_GREEN),
             digitalRead(PIN_BUTTON_RIGHT),
             digitalRead(PIN_BUTTON_LEFT));
  if (timerWakeEnabled) {
    LOG.printf("[sleep] %llu seconds; GPIO3/GPIO4/GPIO5 wake enabled\n",
               static_cast<unsigned long long>(sleepSeconds));
  } else {
    LOG.println("[sleep] waiting for a front button or hardware reset");
  }
  if (buttonWakeResult != ESP_OK &&
      (!timerWakeEnabled || timerWakeResult != ESP_OK)) {
    LOG.println("[sleep] no wake source could be configured; restarting");
    LOG.flush();
    delay(250);
    ESP.restart();
  }
  LOG.flush();
  delay(50);
  hardware::setStatusLed(false);
  esp_deep_sleep_start();
}

}  // namespace

void setup() {
  hardware::setStatusLed(true);
  const esp_sleep_wakeup_cause_t wakeCause =
      esp_sleep_get_wakeup_cause();
  const bool buttonWake = wakeCause == ESP_SLEEP_WAKEUP_EXT1;
  const bool coldBoot = wakeCause == ESP_SLEEP_WAKEUP_UNDEFINED;
  const uint64_t wakePins =
      buttonWake
          ? esp_sleep_get_ext1_wakeup_status()
          : 0;
  pinMode(PIN_BUTTON_GREEN, INPUT_PULLUP);
  pinMode(PIN_BUTTON_RIGHT, INPUT_PULLUP);
  pinMode(PIN_BUTTON_LEFT, INPUT_PULLUP);
  const bool greenWokeDevice =
      (wakePins & (1ULL << PIN_BUTTON_GREEN)) != 0;
  const bool rightWokeDevice =
      (wakePins & (1ULL << PIN_BUTTON_RIGHT)) != 0;
  const bool leftWokeDevice =
      (wakePins & (1ULL << PIN_BUTTON_LEFT)) != 0;

  local_time::configureTimezone(config::TIMEZONE);
  quiet_hours::configure({config::QUIET_HOURS_ENABLED,
                          config::QUIET_START_HOUR,
                          config::QUIET_START_MINUTE,
                          config::QUIET_END_HOUR,
                          config::QUIET_END_MINUTE});
  LOG.begin(115200, SERIAL_8N1, PIN_LOG_RX, PIN_LOG_TX);
  if (app_logic::startupBeepRequired(coldBoot, buttonWake)) {
    // Acknowledge cold boots and button wakes immediately. Holding the green
    // button through this beep and the interval below requests a screenshot.
    hardware::beep();
  }

  bool greenHeldLongEnough = false;
  if (greenWokeDevice) {
    const uint32_t holdStarted = millis();
    uint32_t releaseStarted = 0;
    while (millis() - holdStarted < config::SCREENSHOT_LONG_PRESS_MS) {
      if (!digitalRead(PIN_BUTTON_GREEN)) {
        releaseStarted = 0;
      } else if (releaseStarted == 0) {
        releaseStarted = millis();
      } else if (millis() - releaseStarted >=
                 config::BUTTON_RELEASE_DEBOUNCE_MS) {
        break;
      }
      delay(5);
    }
    greenHeldLongEnough =
        millis() - holdStarted >= config::SCREENSHOT_LONG_PRESS_MS;
  }
  screenshotRequested = greenHeldLongEnough;

  LOG.println();
  LOG.println("============================================");
  LOG.printf(" reTerminal %s standalone Weather / %s\n",
             MODEL_NAME, COLOR_MODE_NAME);
  LOG.println("============================================");
  LOG.printf("[boot] wake cause=%d pins=0x%llx, PSRAM=%luK, "
             "GPIO3=%s GPIO4=%s GPIO5=%s\n",
             wakeCause, static_cast<unsigned long long>(wakePins),
             static_cast<unsigned long>(ESP.getPsramSize() / 1024),
             greenWokeDevice
                 ? (greenHeldLongEnough ? "long-press" : "short-press")
                 : "idle",
             rightWokeDevice ? "wake" : "idle",
             leftWokeDevice ? "wake" : "idle");
  if (screenshotRequested) {
    LOG.println("[screenshot] green-button long press requested export");
    delay(80);
    hardware::beep();
  }

  const time_t startupTime = time(nullptr);
  const bool schedulingClockSuspicious =
      !local_time::clockIsValid() ||
      (lastNtpSyncEpoch > 0 && startupTime < lastNtpSyncEpoch);
  // The ESP32's deep-sleep RTC drifts several percent (internal 150 kHz RC
  // oscillator), so read the PCF8563 on every wake and reset the system
  // clock from it. PCF8563 is battery-backed and stays accurate to ~20 ppm.
  const bool hardwareRtcCheckedEarly = true;
  if (schedulingClockSuspicious) {
    LOG.println("[rtc] schedule clock is invalid or behind retained state; "
                "trying PCF8563");
  }
  rtc_sync::restoreSystemClock();

  bool wakeEventLogged = wake_report::logWakeEvent(wakeCause, wakePins, false);
  const bool ntpDue = config::DEBUG_FORCE_NTP ||
      local_time::refreshDue(coldBoot, lastNtpSyncEpoch, config::NTP_REFRESH_SECONDS);
  if (config::DEBUG_FORCE_NTP) {
    LOG.println("[debug] DEBUG_FORCE_NTP=true, resyncing every wake");
  }
  struct tm localTime = {};
  const bool haveLocalTime = local_time::localClock(localTime);
  if (app_logic::suppressForQuietHours(
          coldBoot, buttonWake, ntpDue, haveLocalTime,
          haveLocalTime && quiet_hours::active(localTime))) {
    const uint64_t quietSleepSeconds = quiet_hours::secondsUntilEnd(localTime);
    LOG.printf("[quiet] refresh suppressed; sleeping until %s\n",
               quiet_hours::endLabel().c_str());
    powerDownAndSleep(quietSleepSeconds);
    return;
  }

  sensors::readAll(PIN_BATTERY_ENABLE, PIN_BATTERY_ADC, sht4, config::SENSOR_READ_ATTEMPTS, config::SENSOR_RETRY_DELAY_MS, sensorReadings);
  if (coldBoot && !hardwareRtcCheckedEarly) {
    pcf8563::Reading storedRtc;
    rtc_sync::readAndLog(storedRtc);
  }
  epaper.begin();
  sdReady = sd_card::mount(epaper.getSPIinstance(), config::CACHE_DIR);
  if (screenshotRequested && !sdReady) {
    LOG.println("[screenshot] request ignored: SD card is unavailable");
    screenshotRequested = false;
  }

  WeatherData weather;
  String liveFailureReason;
  String cacheFailureReason;
  bool cacheChecked = false;
  bool cacheLoaded = false;

  // Validate the cache before composing the cold-boot screen. File existence
  // alone does not mean the saved forecast is recent enough to use.
  if (!buttonWake && local_time::clockIsValid()) {
    cacheChecked = true;
    cacheLoaded = loadCachedWeather(weather, cacheFailureReason);
  }

  const bool showConnectionStatus = coldBoot;
  const String connectionDetail =
      cacheLoaded ? "Live update not required" : "Live update required";
  const String stationMac = wifi_sta::stationMacAddress();
  LOG.printf("[wifi] station MAC=%s\n", stationMac.c_str());

#if RETERMINAL_MODEL == 1001
  if (showConnectionStatus) {
    LOG.println("[display] showing Wi-Fi connection status");
    renderStatus("Connecting to " + String(WIFI_SSID), connectionDetail,
                 stationMac);
  }
  epaper.initGrayMode(GRAY_LEVEL4);
#elif RETERMINAL_MODEL == 1003
  epaper.initGrayMode(GRAY_LEVEL16);
#endif
  epaper.fillSprite(PANEL_WHITE);

#if RETERMINAL_MODEL != 1001
  if (showConnectionStatus) {
    LOG.println("[display] showing Wi-Fi connection status");
    renderStatus("Connecting to " + String(WIFI_SSID), connectionDetail,
                 stationMac);
  }
#endif

  const bool networkRequired = buttonWake || ntpDue || !cacheLoaded;
  const bool networkAvailable =
      networkRequired && wifi_sta::connectStation(WIFI_SSID, WIFI_PASSWORD, config::WIFI_TIMEOUT_MS, &liveFailureReason);
  const bool ntpSynchronized =
      networkAvailable && ntpDue && ntp::synchronizeAndPersist(config::TIMEZONE, config::NTP_SERVER_PRIMARY, config::NTP_SERVER_SECONDARY, config::NTP_DHCP_TIMEOUT_MS, config::NTP_SYNC_TIMEOUT_MS, &lastNtpSyncEpoch);
  bool rtcRestored = false;
  if (ntpDue && !ntpSynchronized && !coldBoot) {
    LOG.println("[ntp] using PCF8563 fallback after synchronization failure");
    rtcRestored = rtc_sync::restoreSystemClock();
  }
  if (coldBoot && ntpDue && !ntpSynchronized) {
    LOG.println("[display] cold boot NTP unavailable; warning user about clock");
    const String warning =
        config::WEATHER_PROVIDER == config::WeatherProvider::QWeather
            ? "Clock not synced - times inaccurate, QWeather may fail"
            : "Clock not synced - displayed times may be inaccurate";
    renderStatus("Connecting to " + String(WIFI_SSID), warning, stationMac);
  }
  local_time::configureTimezone(config::TIMEZONE);
  quiet_hours::configure({config::QUIET_HOURS_ENABLED,
                          config::QUIET_START_HOUR,
                          config::QUIET_START_MINUTE,
                          config::QUIET_END_HOUR,
                          config::QUIET_END_MINUTE});
  if (!wakeEventLogged) {
    wake_report::logWakeEvent(wakeCause, wakePins, true);
  }

  if (!coldBoot && !buttonWake && local_time::localClock(localTime) &&
      quiet_hours::active(localTime)) {
    const uint64_t quietSleepSeconds = quiet_hours::secondsUntilEnd(localTime);
    LOG.printf("[quiet] refresh suppressed after clock sync; sleeping until %s\n",
               quiet_hours::endLabel().c_str());
    wifi_sta::disable();
    powerDownAndSleep(quietSleepSeconds);
    return;
  }

  // Cold boot NTP may have made it possible to validate a cache whose age
  // could not be checked before connecting. Only re-check when the clock's
  // state actually changed (fresh NTP sync or RTC restore) or when the first
  // attempt was skipped because the clock was not yet valid -- otherwise
  // re-running produces the same answer and duplicates the log line.
  if (!buttonWake && !cacheLoaded &&
      (!cacheChecked || ntpSynchronized || rtcRestored) &&
      local_time::clockIsValid()) {
    cacheChecked = true;
    cacheLoaded = loadCachedWeather(weather, cacheFailureReason);
  }

  String liveResponse;
  const bool liveUpdated =
      !cacheLoaded && networkAvailable &&
      fetchWeather(weather, liveResponse, liveFailureReason, buttonWake);
  if (cacheLoaded) {
    LOG.println("[cache] fresh forecast selected; skipping live weather request");
  }
  // The response has already been parsed. Do not keep the radio associated
  // while writing the cache, composing the frame, or refreshing the panel.
  wifi_sta::disable();

  if (liveUpdated && sdReady) {
    String canonical;
    if (!canonical_weather::serialize(weather, canonical)) {
      LOG.println("[cache] forecast serialization failed; skipping save");
    } else if (sd_card::writeFileAtomically(config::FORECAST_CACHE,
                                            canonical)) {
      LOG.println("[cache] saved latest forecast");
    } else {
      LOG.println("[cache] forecast not stored; continuing with live data");
    }
  }
  if (!liveUpdated && !cacheLoaded && !cacheChecked) {
    cacheLoaded = loadCachedWeather(weather, cacheFailureReason);
  }
  const bool haveWeather = liveUpdated || cacheLoaded;
  uint64_t nextSleepSeconds = config::SLEEP_SECONDS;
  if (local_time::localClock(localTime)) {
    if (quiet_hours::active(localTime) ||
        quiet_hours::nextWakeFallsInside(localTime, config::SLEEP_SECONDS)) {
      quietSleepNotice = true;
      nextSleepSeconds = quiet_hours::secondsUntilEnd(localTime);
      LOG.printf("[quiet] this is the final refresh; sleeping until %s\n",
                 quiet_hours::endLabel().c_str());
    }
  }

  if (haveWeather) {
    renderWeather(weather);
  } else {
    // Live weather failed. Fall back to the saved forecast if it is still
    // reasonably fresh; only show the error screen if the cache is older
    // than FAILURE_CACHE_MAX_AGE_SECONDS (or missing).
    String staleFailureReason;
    const bool staleCacheLoaded =
        local_time::clockIsValid() &&
        loadCachedWeather(weather, staleFailureReason,
                          config::FAILURE_CACHE_MAX_AGE_SECONDS);
    if (app_logic::useCachedForecastOnFailure(
            /*liveFetchSucceeded=*/false, local_time::clockIsValid(),
            /*cacheAvailable=*/staleCacheLoaded,
            /*cacheWithinFailureWindow=*/staleCacheLoaded)) {
      LOG.println("[weather] live fetch failed; showing recent cached forecast");
      renderWeather(weather);
      powerDownAndSleep(config::FAILURE_RETRY_SECONDS);
      return;
    }
    if (liveFailureReason.isEmpty())
      liveFailureReason = "Live weather is unavailable";
    if (cacheFailureReason.isEmpty())
      cacheFailureReason = staleFailureReason.isEmpty()
                               ? "No fresh saved forecast is available"
                               : staleFailureReason;
    const String failureSummary =
        liveFailureReason + "; " + cacheFailureReason;
    LOG.printf("[weather] unavailable: %s\n", failureSummary.c_str());
    const uint64_t retryMinutes = config::FAILURE_RETRY_SECONDS / 60ULL;
    const String detail =
        "Retrying in " + String(static_cast<unsigned long>(retryMinutes)) +
        " minutes. Press any button to retry now.";
    renderStatus("Weather unavailable", detail, failureSummary);
    powerDownAndSleep(config::FAILURE_RETRY_SECONDS);
    return;
  }

  powerDownAndSleep(nextSleepSeconds);
}

void loop() {
  delay(1000);
}
