#!/usr/bin/env python3
"""Generate flash-backed VLW arrays for the localized Games interface."""

from __future__ import annotations

import argparse
import importlib.util
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
LOCALIZATION_HEADER = ROOT / "games" / "src" / "game_localization.h"
HELP_TEXT_HEADER = ROOT / "games" / "src" / "game_help_text.h"
OUTPUT_HEADER = ROOT / "games" / "src" / "game_ui_fonts.h"
DEFAULT_FONT = ROOT / "tools" / "fonts" / "NotoSansCJKsc-Bold.otf"
SIZES = (16, 24, 32)


def load_vlw_module():
    module_path = ROOT / "tools" / "fonts" / "make_vlw.py"
    spec = importlib.util.spec_from_file_location("make_vlw", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def required_codepoints(*headers: Path) -> list[int]:
    characters = set(chr(codepoint) for codepoint in range(0x20, 0x7F))
    for header in headers:
        source = header.read_text(encoding="utf-8")
        for value in re.findall(r'u8"((?:[^"\\]|\\.)*)"', source):
            characters.update(value)
    return sorted(ord(character) for character in characters)


def format_array(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16])
        rows.append(f"    {values},")
    return (
        f"inline constexpr uint8_t {name}[] PROGMEM = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--font",
        type=Path,
        default=DEFAULT_FONT,
        help="Noto Sans CJK SC TTF/OTF source.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.font.exists():
        raise SystemExit(
            f"{args.font} is missing; download NotoSansCJKsc-Bold.otf as "
            "documented in tools/fonts/README.md"
        )

    make_vlw = load_vlw_module()
    interface_codepoints = required_codepoints(LOCALIZATION_HEADER)
    help_codepoints = required_codepoints(HELP_TEXT_HEADER)
    available = set(make_vlw.enumerate_codepoints(args.font))
    missing = sorted(
        (set(interface_codepoints) | set(help_codepoints)) - available
    )
    if missing:
        formatted = ", ".join(f"U+{codepoint:04X}" for codepoint in missing)
        raise SystemExit(f"source font is missing required glyphs: {formatted}")
    arrays = []
    for size in SIZES:
        blob = make_vlw.build_vlw(args.font, size, interface_codepoints, "GameUi")
        arrays.append(format_array(f"kGameUiFont{size}", blob))
        print(f"generated {size}px: {len(blob):,} bytes")
    help_blob = make_vlw.build_vlw(args.font, 24, help_codepoints, "GameHelp")
    arrays.append(format_array("kGameHelpFont24", help_blob))
    print(f"generated 24px help: {len(help_blob):,} bytes")

    output = (
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        "// Generated by games/tools/generate_ui_fonts.py from Noto Sans CJK SC Bold.\n"
        "// Noto fonts are licensed under the SIL Open Font License 1.1.\n"
        "namespace game_ui_fonts {\n\n"
        + "\n".join(arrays)
        + "\n}  // namespace game_ui_fonts\n"
    )
    OUTPUT_HEADER.write_text(output, encoding="ascii", newline="\n")
    print(f"wrote {OUTPUT_HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
