#!/usr/bin/env python3
"""Emit weather_quotes_data.h from data/quotes.txt.

Reads the bucketed proverb list at ``weather-viewer/data/quotes.txt``
(bucket headers of the form ``# [BUCKET_NAME]`` followed by one quote
per non-comment, non-blank line) and emits per-bucket ``constexpr
const char* PROGMEM`` arrays plus a ``bucketForWmo(int)`` mapping used
by the runtime picker.

Usage:
    python generate_weather_quotes.py <input.txt> <output-header>

Model-agnostic: the same header is used across all four boards. The
per-env output dir is still separate so parallel `pio run` doesn't
race, but the contents don't change with RETERMINAL_MODEL.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BUCKET_HEADER = re.compile(r"^#\s*\[([A-Z_]+)\]")

# Canonical bucket order. Also serves as the enum order in the emitted
# header so runtime lookup is O(1).
BUCKETS = [
    "CLEAR",
    "PARTLY_CLOUDY",
    "OVERCAST",
    "FOG",
    "HAZE",
    "DRIZZLE",
    "RAIN",
    "SHOWERS",
    "THUNDERSTORM",
    "SNOW",
    "SLEET",
    "WIND",
    "COLD",
    "HEAT",
    "UNIVERSAL",
]


def parse_quotes(text: str) -> dict[str, list[str]]:
    """Split ``text`` into ``{BUCKET: [quote, quote, ...]}``.

    Lines starting with ``#`` are comments (skipped). Blank lines are
    skipped. A ``# [BUCKET]`` header switches the current bucket.
    Anything before the first bucket header is a fatal error so we
    don't silently drop lines that were added by mistake.
    """
    result: dict[str, list[str]] = {b: [] for b in BUCKETS}
    current: str | None = None
    for line_no, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        m = BUCKET_HEADER.match(line)
        if m:
            current = m.group(1)
            if current not in result:
                raise SystemExit(
                    f"quotes.txt:{line_no}: unknown bucket [{current}]. "
                    f"Add it to BUCKETS in generate_weather_quotes.py."
                )
            continue
        if line.startswith("#"):
            continue
        if current is None:
            raise SystemExit(
                f"quotes.txt:{line_no}: quote before any bucket header"
            )
        result[current].append(line)
    return result


def c_escape(s: str) -> str:
    """Escape ``s`` for a C string literal. The proverbs only use
    ASCII plus the occasional apostrophe, so a minimal escape covers
    everything we ship."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(quotes: dict[str, list[str]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as w:
        w.write(
            "// Auto-generated by tools/generate_weather_quotes.py from\n"
            "// data/quotes.txt. Do not edit by hand.\n"
            "\n"
            "#pragma once\n"
            "\n"
            "#include <Arduino.h>\n"
            "#include <pgmspace.h>\n"
            "#include <stddef.h>\n"
            "\n"
            "namespace weather_quotes {\n"
            "namespace generated {\n"
            "\n"
            "enum Bucket : uint8_t {\n"
        )
        for i, b in enumerate(BUCKETS):
            w.write(f"  BUCKET_{b} = {i},\n")
        w.write(
            f"  BUCKET_COUNT = {len(BUCKETS)},\n"
            "};\n\n"
        )

        # Per-bucket arrays.
        for b in BUCKETS:
            items = quotes[b]
            w.write(f"inline constexpr size_t kCount_{b} = {len(items)};\n")
            if items:
                w.write(
                    f"inline constexpr const char* const kQuotes_{b}"
                    f"[kCount_{b}] = {{\n"
                )
                for q in items:
                    w.write(f'    "{c_escape(q)}",\n')
                w.write("};\n\n")
            else:
                w.write(
                    f"inline constexpr const char* const* kQuotes_{b}"
                    " = nullptr;\n\n"
                )

        # Lookup table by bucket enum.
        w.write(
            "struct BucketRef {\n"
            "  const char* const* quotes;\n"
            "  size_t count;\n"
            "};\n\n"
            "inline constexpr BucketRef kBuckets[BUCKET_COUNT] = {\n"
        )
        for b in BUCKETS:
            w.write(f"  {{ kQuotes_{b}, kCount_{b} }},  // BUCKET_{b}\n")
        w.write("};\n\n")

        w.write("}  // namespace generated\n")
        w.write("}  // namespace weather_quotes\n")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input", type=Path, help="quotes.txt source")
    p.add_argument("output", type=Path, help="generated header path")
    args = p.parse_args()
    quotes = parse_quotes(args.input.read_text(encoding="utf-8"))
    emit(quotes, args.output)
    total = sum(len(v) for v in quotes.values())
    print(f"generated {args.output} ({total} quotes)", file=sys.stderr)


if __name__ == "__main__":
    main()
