from __future__ import annotations

import random
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "sudoku_puzzles.h"
PUZZLE_COUNT = 12
GIVEN_COUNT = 38


def solution_for(seed: int) -> list[int]:
    rng = random.Random(seed)
    bands = rng.sample(range(3), 3)
    stacks = rng.sample(range(3), 3)
    rows = [band * 3 + row for band in bands for row in rng.sample(range(3), 3)]
    columns = [
        stack * 3 + column
        for stack in stacks
        for column in rng.sample(range(3), 3)
    ]
    digits = rng.sample(range(1, 10), 9)
    return [
        digits[(rows[row] * 3 + rows[row] // 3 + columns[column]) % 9]
        for row in range(9)
        for column in range(9)
    ]


def solution_count(cells: list[int], limit: int = 2) -> int:
    board = cells.copy()
    count = 0

    def solve() -> None:
        nonlocal count
        if count >= limit:
            return
        best_index = -1
        best_candidates: list[int] | None = None
        for index, value in enumerate(board):
            if value:
                continue
            row, column = divmod(index, 9)
            used = set(board[row * 9 : row * 9 + 9])
            used.update(board[column::9])
            box_row = row // 3 * 3
            box_column = column // 3 * 3
            used.update(
                board[(box_row + offset_row) * 9 + box_column + offset_column]
                for offset_row in range(3)
                for offset_column in range(3)
            )
            candidates = [digit for digit in range(1, 10) if digit not in used]
            if not candidates:
                return
            if best_candidates is None or len(candidates) < len(best_candidates):
                best_index = index
                best_candidates = candidates
                if len(candidates) == 1:
                    break
        if best_candidates is None:
            count += 1
            return
        for digit in best_candidates:
            board[best_index] = digit
            solve()
            board[best_index] = 0

    solve()
    return count


def puzzle_for(solution: list[int], seed: int) -> list[int]:
    rng = random.Random(seed ^ 0x5A17)
    puzzle = solution.copy()
    positions = list(range(81))
    rng.shuffle(positions)
    for index in positions:
        if sum(value != 0 for value in puzzle) <= GIVEN_COUNT:
            break
        previous = puzzle[index]
        puzzle[index] = 0
        if solution_count(puzzle) != 1:
            puzzle[index] = previous
    if sum(value != 0 for value in puzzle) != GIVEN_COUNT:
        raise ValueError(f"seed {seed}: could not reach {GIVEN_COUNT} givens")
    return puzzle


def format_rows(values: list[int]) -> str:
    return "\n".join(
        "      {" + ", ".join(map(str, values[row * 9 : row * 9 + 9])) + "},"
        for row in range(9)
    )


def generate() -> str:
    definitions: list[str] = []
    for index in range(PUZZLE_COUNT):
        solution = solution_for(0xE1005 + index * 97)
        puzzle = puzzle_for(solution, 0xE1005 + index * 97)
        definitions.append(
            "    {\n"
            "      {\n"
            f"{format_rows(puzzle)}\n"
            "      },\n"
            "      {\n"
            f"{format_rows(solution)}\n"
            "      },\n"
            "    },"
        )

    return f"""#pragma once

#include <stdint.h>

// Generated by tools/generate_sudoku_header.py. The puzzles are derived
// deterministically from randomized valid Sudoku grids and retain one solution.
namespace sudoku_puzzles {{

inline constexpr uint8_t kPuzzleCount = {PUZZLE_COUNT};

struct Puzzle {{
  uint8_t givens[9][9];
  uint8_t solution[9][9];
}};

inline constexpr Puzzle kPuzzles[kPuzzleCount] = {{
{chr(10).join(definitions)}
}};

}}  // namespace sudoku_puzzles
"""


def main() -> None:
    OUTPUT.write_text(generate(), encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
